### ISSUE TITLE
Please update the `latest` tag to v1.4.2

### ISSUE THREAD

**Issue by benlorenz** [julia-actions/julia-buildpkg#35]
The `latest` tag currently points to v1.3.2 which causes an error on julia nightly (see https://github.com/julia-actions/julia-buildpkg/issues/34), due to https://github.com/JuliaLang/julia/pull/50974.
In the latest release `v1` (v1.4.2) the file causing the error was removed.

**Comment by SaschaMann** [comment]
I would strongly suggest not using latest but instead using `@v1` (or better yet, a commit hash of a release) and setting up Dependabot to update it in case there's ever a breaking change to this action. When using `@latest`, it's implied the action may break at any time.

**Comment by JeffFessler** [comment]
> I would strongly suggest not using `@latest`

seems like this advice belongs in the readme for the repo.
i'd been using `@latest` in many repos (just by copying an example yml file from some repo that i thought was well maintained) and i just learned about the advice to _not_ use it because it was deprecated over at [actions/setup-julia](https://github.com/julia-actions/setup-julia/issues/403)
