### ISSUE TITLE
Deprecation warning on `@v1`

### ISSUE THREAD

**Issue by lgoettgens** [julia-actions/julia-buildpkg#36]
I get a deprecation warning to not use `@master` anymore, although I already use `@v1`. See eg here: https://github.com/oscar-system/Oscar.jl/actions/runs/6278947815/job/17062217305#step:4:11

Cc @SaschaMann

**Comment by lgoettgens** [comment]
I think the problem boils down to the `v1.4.3` being on `master` instead of `main`. The former contains the deprecation, while the latter has a newly merged change that probably should have been released.

**Comment by mortenpi** [comment]
I also noticed this in my repos. I feel that 1.4.3 should be yanked (if that's a thing we can do) and 1.4.4 tagged.

**Comment by SaschaMann** [comment]
Sorry for this!

I've tagged `v1.4.4`, `v1.4`, and `v1` (and `latest`) appropriately now.

I am unsure what to do about `v1.4.3` because I don't know if it will confuse Dependabot if we just delete it. I think it may be best to just leave it.

---

Quick explanation of how this happened:

A while ago the main branch was renamed and after finding out that people still use `@master` and GitHub does not forward branch tags for actions in the same manner it forwards branches everywhere else, we've added the deprecation warning. Mainly because regardless of the branch name, using ` @master`/`@main` is a bad idea as there are no stability guarantees whatsoever.

As a result of adding that warning, I was still on `master` locally when tagging the recent release. Because all these actions are quite inconsistent in naming and tags and the rename was 6 months ago, I hadn't noticed this was wrong. I've since deleted the branch locally to prevent further confusion.

There was one "warning" I ignored: the release note generation button didn't generate anything. This could've pointed out an issue with the tags but I didn't make the connection and wrote the release notes manually instead. Now I know that should be treated as a warning sign 😅 

I think the main take away is that we should look into harmonising naming and versioning of the various julia-actions as that would also allow us to script the release process or use an action, making it less prone to errors.
